**Tugas Individu Machine Learning**

Nama : A. Rifqi Afwan Muslihani

NIM  : 20/462174/PA/20146

No. 1

Import dan ambil semua library/alat yang kita akan pakai

In [35]:
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import numpy as np
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


Ambil dataset yang ditelah disimpan di dalam drive

In [36]:
habermandata = pd.read_csv('/content/gdrive/MyDrive/ColabNotebooks/haberman.data',header=None)
habermandata.head()

0   1  2  3
0  30  64  1  1
1  30  62  3  1
2  30  65  0  1
3  31  59  2  1
4  31  65  4  1

Split the dataset dengan tes_size = 0.2

In [37]:
X = habermandata.iloc[:, [0, 1, 2]].values
y = habermandata.iloc[:, -1].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

Scaling dataset

In [38]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## **Train Dataset dengan Algoritma KKN**

In [39]:
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [40]:
y_pred = classifier.predict(X_test)
y_test

array([2, 1, 2, 1, 2, 1, 2, 2, 2, 1, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 2,
       1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 1])

In [41]:
y_pred

array([1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [42]:
MatrixC = confusion_matrix(y_test, y_pred)
ReportC = classification_report(y_test,y_pred)
ScoreA = accuracy_score(y_test,y_pred)

print('Confusion matrix = ')
print(MatrixC)
print('Testing Accuracy = {}'.format(ScoreA))
print('classification report = ')
print(ReportC)

Confusion matrix = 
[[34  3]
 [20  5]]
Testing Accuracy = 0.6290322580645161
classification report = 
              precision    recall  f1-score   support

           1       0.63      0.92      0.75        37
           2       0.62      0.20      0.30        25

    accuracy                           0.63        62
   macro avg       0.63      0.56      0.53        62
weighted avg       0.63      0.63      0.57        62



## **Train Dataset dengan Algoritma NaiveBayes**

In [43]:
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [44]:
y_pred = classifier.predict(X_test)

In [45]:
MatrixC = confusion_matrix(y_test, y_pred)
ReportC = classification_report(y_test,y_pred)
ScoreA = accuracy_score(y_test,y_pred)

print('Confusion matrix = ')
print(MatrixC)
print('Testing Accuracy = {}'.format(ScoreA))
print('classification report = ')
print(ReportC)

Confusion matrix = 
[[36  1]
 [23  2]]
Testing Accuracy = 0.6129032258064516
classification report = 
              precision    recall  f1-score   support

           1       0.61      0.97      0.75        37
           2       0.67      0.08      0.14        25

    accuracy                           0.61        62
   macro avg       0.64      0.53      0.45        62
weighted avg       0.63      0.61      0.51        62



# **Train Dataset dengan SVM**

In [46]:
classifier = SVC(kernel='linear',random_state=0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [47]:
y_pred = classifier.predict(X_test)

In [52]:
ScoreA = accuracy_score(y_test,y_pred)
ReportC = classification_report(y_test,y_pred)
MatrixC = confusion_matrix(y_test, y_pred)
print('Confusion matrix = ')
print(MatrixC)
print('Testing Accuracy = {}'.format(ScoreA))
print('classification report = ')
print(ReportC)

Confusion matrix = 
[[37  0]
 [25  0]]
Testing Accuracy = 0.5967741935483871
classification report = 
              precision    recall  f1-score   support

           1       0.60      1.00      0.75        37
           2       0.00      0.00      0.00        25

    accuracy                           0.60        62
   macro avg       0.30      0.50      0.37        62
weighted avg       0.36      0.60      0.45        62



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Berdasarkan data yang ada dapat dilihat bahwa Algoritma KKN yang terbaik untuk classifier pada dataset ini